# Generated by Django 3.2.18 on 2023-05-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoinZeply', '0002_rename_category_coin'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='coin_image',
            field=models.ImageField(default='CoinZeply/default.jpg', upload_to='CoinZeply/'),
        ),
    ]
