# Generated by Django 3.2.18 on 2023-04-28 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CoinZeply', '0002_rename_category_coin'),
        ('WalletZeply', '0002_wallet_wallet_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressUC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressUC_address', models.CharField(max_length=255)),
                ('addressUC_des', models.TextField(null=True)),
                ('addressUC_created_date', models.DateTimeField(auto_now_add=True)),
                ('addressUC_Coinid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CoinZeply.coin')),
                ('addressUC_walletid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='WalletZeply.wallet')),
            ],
        ),
    ]
